# Site settings
title: 4 UP
subtitle: "Uma empresa focada nos resultados da sua!"
url: "https:digitalup.com.br"
baseurl: ""
cover: "/assets/cover.png"
logo: "/assets/logo.png"

exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

# Links
links:
  facebook: null
  twitter: null
  google-plus: null
  youtube: null
  pinterest: null
  linkedin: null
  dribbble: null
  behance: null

# Build settings
markdown: kramdown

# Google analytics
ga_tracking_id: null

#Disqus
disqus: 'https-leonecorrea-com'
comments: true

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."

autor:
  name: "Leone Corrêa"
  description: "CEO-DigitalUP"

estatistics:
  comments: 260
  projects: 50
  days: 30
  clients: 34

permalink: /:title

contato:
  telefone: '+55031995540438'
  email: contato@4up.com.br
  endereco:
    cidade: Belo Horizonte
    estado: Minas Gerais
    pais: Brasil